const cookie = [
    {
        "domain": ".s.weibo.com",
        "expirationDate": 1558771954,
        "hostOnly": false,
        "httpOnly": false,
        "name": "un",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "13410192936",
        "id": 1
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1600445103,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__gads",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ID=9d2e988b7286d812:T=1537373103:S=ALNI_MaRmnIaFfn3DK-iKugBOS4zM9W4lw",
        "id": 2
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1600445054,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.1377904220.1537373054",
        "id": 3
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_s_tentry",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "-",
        "id": 4
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1558512753.478569,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ALF",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1558512753",
        "id": 5
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "Apache",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "4672902249779.496.1557907908876",
        "id": 6
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1873267954.478168,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SCF",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AuzPZ5nom15nw9BbvlwP-9wtRJ0UyLSO3enH-qhBUgV-x7-z5GyOhDjd8db_SHbB4pLzPS27TZYaextkGHZhBeE.",
        "id": 7
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1840252893,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SINAGLOBAL",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "3663343293146.999.1524892893985",
        "id": 8
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "SSOLoginState",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "1557907954",
        "id": 9
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "SUB",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "_2A25x37miDeRhGeBH4loV9CnMzz2IHXVSrKxqrDV8PUNbmtBeLRXxkW9NQYyNOhgS07mvteQMtthMr6LYYwLATWUQ",
        "id": 10
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1589443954.47832,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SUBP",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0033WrSXqPxfM725Ws9jqgMF55529P9D9W5OoKVnxl-uxN1AlIJ-YI1f5JpX5K2hUgL.Foq41KnXShM7Sh22dJLoIp7LxKML1KBLBKnLxKqL1hnLBoMc1K.RShBNehBp",
        "id": 11
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1589443954.478369,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SUHB",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "05i6X3MRg8gN45",
        "id": 12
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1589011908,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ULV",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1557907908975:3:3:2:4672902249779.496.1557907908876:1557737927287",
        "id": 13
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1558247510,
        "hostOnly": false,
        "httpOnly": false,
        "name": "un",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "13410192936",
        "id": 14
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1589273927,
        "hostOnly": false,
        "httpOnly": false,
        "name": "UOR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": ",,login.sina.com.cn",
        "id": 15
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1557988312.459586,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wvr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "6",
        "id": 16
    },
    {
        "domain": "s.weibo.com",
        "expirationDate": 1557908556,
        "hostOnly": true,
        "httpOnly": false,
        "name": "WBStorage",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "e4e08ad1044aa883|undefined",
        "id": 17
    },
    {
        "domain": "s.weibo.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "WBtopGlobal_register_version",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "5c10f3128cf400c5",
        "id": 18
    }
];
module.exports = cookie;